server:
  port: ${CONFIG_PORT}

spring:
  application:
    name: config-service
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_ID}
    password: ${RABBITMQ_PWD}
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_CONFIG_URL}
          username: ${GITHUB_CONFIG_ID}
          password: ${GITHUB_CONFIG_PWD}
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
