
server:
  port: 9090

spring:
  application:
    name: project-service
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: S09P12A608
#    password: asdf1234
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12A608
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 50
#      connection-init-sql: SELECT 1
#      connection-timeout: 5000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      auto-commit: true


eureka:
  instance:
    instance-id: ${spring.application.name}.{spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone:
        http://localhost:8761
    fetch-registry: false
    register-with-eureka: false

#logging:
#  level:
#    root:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

