server:
  port: 8081

spring:
  application:
    name: user-service

  rabbitmq:
    host: ${SERVER_IP}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_ID}
    password: ${RABBITMQ_PWD}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 12345

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: user-service
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bus-refresh, info, metrics, prometheus # 포함시킬 내용들
