server:
  port: 8001

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33060/santa
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 50389ab406794f10677cfc8b7e3bcf4d
            client-secret: bz2JnPOVnr8G9y907sRzdQIWGLcTbAr3
            redirect-uri: http://localhost:8001/login/oauth2/code/kakao
            client-authentication-method: POST # 카카오 접근시 고정값
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # 인가 코드
            token-uri: https://kauth.kakao.com/oauth/token              # 토큰 받기
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${MY_IP_ADDRESS}
  client:
    service-url:
      defaultZone: http://i9a608.p.ssafy.io:8761/eureka
    fetch-registry: true
    register-with-eureka: true



logging:
  level:
    com.example.user-service.client: DEBUG # Feign Client Logging 설정

jwt:
  secret: asdfghjklqwertyuiopzxcvbnmasdfasdfweasdfwbzzgoooodItstootireddgdsasdfsawherhdsfbdfsgsadfsadvsvethegwfsdavbdfh
  token-validity-in-milliseconds: 100000000
  refresh-token: 987654321987654321
  refresh-token-limit-days: 1
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bus-refresh, info, metrics, prometheus # 포함시킬 내용들

cloud:
  aws:
    credentials:
      accessKey: AKIAQPOZGAOT652M75EC
      secretKey: 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
    stack:
      auto: false
    s3:
      bucket: ssafysanta
    region:
      static: ap-northeast-2


