server:
  port: 8081

#spring:
#  # 이메일 설정
#  mail:
##    protocol: smtps
#    port: 587
#    host: smtp.gmail.com
#    username: memoryrevive608@gmail.com
#    password: xmluoinhdtlviydr
#    properties:
#      mail:
##        port: 587
#        smtp.auth: true
#        smtp.starttls.enable: true
##        smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
spring:
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: memoryrevive608@gmail.com
    password: xmluoinhdtlviydr
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
#  h2:
#    console:
#      enabled: true
#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ssafy

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: S09P12A608
#    password: asdf1234
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12A608
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 50
#      connection-init-sql: SELECT 1
#      connection-timeout: 5000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      auto-commit: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    defer-datasource-initialization: true

logging:
  level:
    #    me.silvernine: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace

